---
project_name: trestle
token: trestletoken
tmp_location: /tmp/trestle
version:
  k3s: v1.21.4+k3s1
  kubectl: v1.21.4
  helm: v3.6.3
  kubeconform: v0.4.8
monitoring:
  target_namespace: monitoring
  ingress:
    prometheus: prometheus.example.com
    grafana: grafana.example.com
metallb:
  target_namespace: metallb
  address_range: 192.168.122.130-192.168.122.140
