---
project_name: trestle
token: trestletoken
tmp_location: /tmp/trestle
nfs_location: /srv/nfs/trestle
version:
  k3s: v1.22.2+k3s2
  kubectl: v1.22.2
  helm: v3.6.3
  argocd: v2.1.3
metallb:
  target_namespace: metallb
  address_range: 192.168.122.130-192.168.122.140
  # all LB ip values should be inside "address_range"
  lb_ip:
    traefik: 192.168.122.130
    grafana: 192.168.122.131
    prometheus: 192.168.122.132
    argocd: 192.168.122.133
monitoring:
  target_namespace: monitoring
nfs_provisioner:
  target_namespace: nfs-provisioner
argocd:
  target_namespace: argocd
