---
project_name: trestle
token: trestletoken
tmp_location: /tmp/trestle
nfs_location: /srv/nfs/trestle
dns_suffix: trestle.local
version:
  k3s: v1.27.7+k3s1
  kubectl: v1.27.7
  helm: v3.12.3
  argocd: v2.8.6
metallb:
  enabled: true
  target_namespace: metallb
  address_range: 192.168.122.130-192.168.122.150
  # all LB ip values should be inside "address_range"
  lb_ip:
    traefik: 192.168.122.130
    grafana: 192.168.122.131
    prometheus: 192.168.122.132
    argocd: 192.168.122.133
    kubernetes_dashboard: 192.168.122.134
traefik:
  target_namespace: traefik
monitoring:
  target_namespace: monitoring
nfs_provisioner:
  target_namespace: nfs-provisioner
argocd:
  target_namespace: argocd
kubernetes_dashboard:
  target_namespace: kubernetes-dashboard
