---
# handlers file for client
- name: start haproxy service
  become: yes
  systemd:
    name: haproxy
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: start nfs service
  become: yes
  systemd:
    name: nfs-kernel-server
    state: restarted
    daemon_reload: yes
    enabled: yes
