---
# tasks file for worker
- name: install packages
  become: yes
  package:
    state: present
    name:
      - nfs-common

- name: setup system directory
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/rancher/k3s
    - /var/log/rancher/k3s

- name: create k3s config.yaml
  become: yes
  template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    mode: 0600

- name: set k3s binary
  set_fact:
    k3s_binary: "{{ 'k3s-arm64' if ansible_architecture == 'aarch64' else 'k3s' }}"

- name: download k3s
  become: yes
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ version.k3s }}/{{ k3s_binary }}
    dest: /usr/local/bin/k3s
    mode: 0755
    timeout: 60

- name: create k3s systemd service file
  become: yes
  copy:
    src: k3s-agent.service
    dest: /etc/systemd/system/
    mode: 0644
  notify: start k3s-agent service
