---
# tasks file for common
- name: get git version
  shell: git rev-parse --short HEAD
  delegate_to: localhost
  args:
    chdir: "{{ playbook_dir }}"
  register: git_result

- name: set git commit
  set_fact:
    git_commit: "{{ git_result.stdout }}"

- name: push release file
  become: yes
  template:
    src: trestle-release.j2
    dest: /etc/trestle-release

- name: install packages
  become: yes
  package: name={{ item }} state=present
  with_items:
    - jq
    - tree
    - sysstat

- name: remove snaps
  become: yes
  snap: name={{ item }} state=absent
  with_items:
    - lxd
    - core18
    - snapd

- name: enable sysstat
  become: yes
  replace:
    path: /etc/default/sysstat
    regexp: 'ENABLED="false"'
    replace: 'ENABLED="true"'
