---
# tasks file for common
- name: get git version  # noqa command-instead-of-module no-changed-when
  command: git rev-parse --short HEAD
  delegate_to: localhost
  args:
    chdir: "{{ playbook_dir }}"
  register: git_result

- name: set git commit
  set_fact:
    git_commit: "{{ git_result.stdout }}"

- name: push release file
  become: yes
  template:
    src: trestle-release.j2
    dest: /etc/trestle-release
    mode: 0644

- name: stop services
  become: yes
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - snapd
    - unattended-upgrades

- name: install packages
  become: yes
  package: name={{ item }} state=present
  with_items:
    - jq
    - tree
    - sysstat

- name: enable sysstat
  become: yes
  replace:
    path: /etc/default/sysstat
    regexp: 'ENABLED="false"'
    replace: 'ENABLED="true"'
  notify: start sysstat service
