---
# tasks file for master
- name: setup system directory
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/rancher/k3s
    - /var/log/rancher/k3s
    - /var/lib/rancher/k3s/server/manifests/trestle

- name: copy traefik manifest
  become: yes
  template:
    src: "{{ item }}"
    dest: "/var/lib/rancher/k3s/server/manifests/{{ item | splitext | first }}"
    mode: 0600
  with_items:
    - traefik-helm-chart-config.yaml.j2

- name: copy metallb helm manifest
  become: yes
  template:
    src: "{{ item }}"
    dest: "/var/lib/rancher/k3s/server/manifests/trestle/{{ item | splitext | first }}"
    mode: 0600
  with_items:
    - metallb-helm-chart.yaml.j2
  when: metallb.enabled == true


- name: copy helm manifests
  become: yes
  template:
    src: "{{ item }}"
    dest: "/var/lib/rancher/k3s/server/manifests/trestle/{{ item | splitext | first }}"
    mode: 0600
  with_items:
    - nfs-provisioner-helm-chart.yaml.j2
    - argo-cd-helm-chart.yaml.j2
    - kube-prometheus-stack-helm-chart.yaml.j2
    - loki-stack-helm-chart.yaml.j2

- name: create k3s config.yaml
  become: yes
  template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    mode: 0600

- name: set k3s binary
  set_fact:
    k3s_binary: "{{ 'k3s-arm64' if ansible_architecture == 'aarch64' else 'k3s' }}"

- name: download k3s
  become: yes
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ version.k3s }}/{{ k3s_binary }}
    dest: /usr/local/bin/k3s
    mode: 0755
    timeout: 60

- name: create k3s systemd service file
  become: yes
  copy:
    src: k3s.service
    dest: /etc/systemd/system/
    mode: 0644
  notify: start k3s service
