---
name: CI

# yamllint disable-line
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run yamllint
        run: yamllint .
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
