---
name: CI

# yamllint disable-line
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Print python version
        run: python --version
      - name: Install ansible lint
        run: pip install ansible-lint ansible-core
      - name: Print ansible-lint version
        run: ansible-lint --version
      - name: Run yamllint
        run: yamllint .
      - name: Run ansible-lint
        run: ansible-lint
