---
name: CI

# yamllint disable-line
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print python version
        run: python3 --version
      - name: Install ansible-lint
        run: pip install ansible-lint
      - name: Print ansible-lint version
        run: ansible-lint --version
      - name: Run yamllint
        run: yamllint .
      - name: Run ansible-lint
        run: ansible-lint
